# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Efeyamann.Streamlity
PackageVersion: 0.1.0
InstallerType: inno
UpgradeBehavior: install
ProductCode: '{56EA4FDC-4D6A-4DA1-8A54-B7A29F12C5E2}_is1'
AppsAndFeaturesEntries:
- DisplayName: Streamlity 0.1.0
  Publisher: Streamlity
  ProductCode: '{56EA4FDC-4D6A-4DA1-8A54-B7A29F12C5E2}_is1'
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/Efeyamann/Streamlity/releases/download/v0.1.0/Streamlity-0.1.0-windows-x64-setup.exe
  InstallerSha256: C1C4F80E16A6CD9AED7BE7669A50B03686A5CB8ABC22F73ACA00820C1EA02540
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/Efeyamann/Streamlity/releases/download/v0.1.0/Streamlity-0.1.0-windows-x64-setup.exe
  InstallerSha256: C1C4F80E16A6CD9AED7BE7669A50B03686A5CB8ABC22F73ACA00820C1EA02540
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-09-28
